### ISSUE TITLE
No bind_transciever response from the simulator on reconnecting 

### ISSUE THREAD

**Issue by elhananjair** [ukarim/smscsim#12] opened 2024-03-02 12:21 UTC
Hello @ukarim I love this tool, I am testing it with my nodejs web application. Recently I have started working on a scenario when SMSC closes the session and how I can retry connecting to the SMSC. I implemented the reconnection like this: 

```
    session.on('close', () => {
        console.log("Connection to SMSC closed, trying to reconnect...");
        save_smsc_status(0).then(() => {
            session.socket.setTimeout(1000);
            session.socket.on('timeout', function() {
              console.log('socket timeout');
              session.destroy();
            });
            session.connect();
        }).catch("Error saving SMSC connection status...")

    })

```
and to test this scenario, I stop the simulator in the middle after the first bind, and restart it while the application retries to reconnect. But the result is not what I was expecting. The simulator shows a bind request but no response, as a result, a function such as `submit_sm` won't processed as it waits for a successful bind_response. 

Any ideas on this? 

```
2024/03/02 15:05:41 bind request from system_id[0154146]
2024/03/02 15:05:51 enquire_link from system_id[0154146]
2024/03/02 15:06:01 enquire_link from system_id[0154146]
2024/03/02 15:06:11 enquire_link from system_id[0154146]

```

**Comment by ukarim** [comment] 2024-03-05 16:31
@elhananjair  for smscsim there is no difference between connect and reconnect. It just not wrote logs about response pdus. Added this additional logs in latest commit, you can use new version now.
It seems the problem is on the smpp client side

**Comment by ukarim** [comment] 2024-03-06 08:11
I dont know what library you are using, but it looks like you should call 'destroy' method, wait until completion, and only then call 'connect' methodSent from my Galaxy

**Comment by elhananjair** [comment] 2024-03-06 19:51
@ukarim thank you for replying, I am using `node-smpp` nodejs SMPP library. I find it difficult to implement reconnecting to SMSC if the connection is closed from SMSC or if there is an issue. 

I tried to implement running `session.distroy()` to clean up the mess but no luck, therefore I added a new variable to check if there is a reconnect request, and then based on that I will execute the next operations. There is no good example in this area. Let me share with you the code I am writing:

```
let isReconnect = false
...
  session.on('close', () => {
            console.log("Connection to SMSC closed, trying to reconnect...");
            save_smsc_status(0).then(() => {
                session.socket.setTimeout(1000);
                session.socket.on('timeout', function () {
                    console.log('socket timeout');
                    session.destroy();
                });
                setTimeout(() => {
                    session.connect();
                    session.resume();
                    isReconnect = true; 
                }, 10000)
            }).catch("Error saving SMSC connection status...")

        })
```

**Comment by ukarim** [comment] 2024-05-05 14:17
@elhananjair  sorry, can't help with node-smpp. Hope you already found the solutions.
Closing this issue

**Closed as completed by ukarim** 2024-05-05 14:17 UTC
